# Configuration for issue-states - https://github.com/dessant/issue-states

# Open issues that are moved to these project columns. Set to `[]` to disable
openIssueColumns:
  - To do
  - In Progress
  - Needs review
  - Reviewer approved

# Close issues that are moved to these project columns. Set to `[]` to disable
closedIssueColumns:
  - Closed
  - Done
# Repository to extend settings from
# _extends: repo
