# Configuration for probot-stale - https://github.com/probot/stale

# Number of days of inactivity before an Issue or Pull Request becomes stale
daysUntilStale: 60

# Number of days of inactivity before an Issue or Pull Request with the stale label is closed.
# Set to false to disable. If disabled, issues still need to be closed manually, but will remain marked as stale.
daysUntilClose: 14

# Issues or Pull Requests with these labels will never be considered stale. Set to `[]` to disable
exemptLabels:
  - 'Status: On Hold :stop_sign:'
  - 'Type: Vulnerability :warning'
  - security
  - 'Status: Accepted :heavy_check_mark:'

# Set to true to ignore issues in a project (defaults to false)
exemptProjects: false

# Set to true to ignore issues in a milestone (defaults to false)
exemptMilestones: false

# Label to use when marking as stale
staleLabel: 'Status: Left Out :left_luggage:'

# Comment to post when marking as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.

# Comment to post when removing the stale label.
unmarkComment: >
  This issue is no longer stale.

# Comment to post when closing a stale Issue or Pull Request.
closeComment: >
  This issue has been stale for 14 days so I'm closing it.

# Limit the number of actions per hour, from 1-30. Default is 30
limitPerRun: 30
