language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - 'stable'
  - 'lts/*'
install:
  - npm i
script:
  - npm run auth
  - npm run validate
  - npm run cov
after_success:
  - snyk monitor
jobs:
  include:
    - stage: release
      node_js: 'node'
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: npm run sr
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
stages:
  - name: test
  - name: release
    if: branch = master
